# Generated by Django 5.2.1 on 2025-06-13 21:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='funeral_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donation_for', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana Cedis (GHS)'), ('USD', 'US Dollars (USD)'), ('EUR', 'Euros (EUR)'), ('GBP', 'British Pounds (GBP)')], default='GHS', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('cheque', 'Cheque')], max_length=10)),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='mysite.funeral')),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
