# Generated by Django 5.2.1 on 2025-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='ecobank_logo',
            field=models.ImageField(default='ecobank_logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='fnet_logo',
            field=models.ImageField(default='fnet_logo.jpg', upload_to=''),
        ),
    ]
