# Generated by Django 5.2.1 on 2025-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_donation_ecobank_logo_donation_fnet_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
